"""empty message

Revision ID: 508cfca35ee9
Revises: 2252374139ef
Create Date: 2024-04-13 00:10:16.327863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508cfca35ee9'
down_revision = '2252374139ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods_needed',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_foods_needed'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foods_needed')
    # ### end Alembic commands ###
