"""empty message

Revision ID: b7094f27b71c
Revises: 508cfca35ee9
Create Date: 2024-04-13 00:32:00.180908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7094f27b71c'
down_revision = '508cfca35ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods_needed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memo', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods_needed', schema=None) as batch_op:
        batch_op.drop_column('memo')

    # ### end Alembic commands ###
